CREATE TABLE GENRE (
genre_id INT auto_increment PRIMARY KEY,
description VARCHAR(60) UNIQUE NOT NULL
);

CREATE TABLE GAME (
game_id INT auto_increment UNIQUE,
genre_id INT NOT NULL,
name VARCHAR(60) NOT NULL,
publisher VARCHAR(60) NOT NULL,
description VARCHAR(300),
game_image VARCHAR(200),
video VARCHAR(60) NOT NULL,
PRIMARY KEY (name, publisher),
FOREIGN KEY (genre_id) REFERENCES GENRE(genre_id)
);
-- ALTER TABLE GAME ADD FOREIGN KEY(genre_id) REFERENCES GENRE (genre_id)

CREATE TABLE USER (
user_id INT auto_increment PRIMARY KEY,
email VARCHAR(60) UNIQUE,
name VARCHAR(60),
phone_number VARCHAR(12),
password VARCHAR(100)
);

CREATE TABLE FAVORITE (
user_id INT,
game_id INT,
PRIMARY KEY (user_id, game_id),
FOREIGN KEY (user_id) REFERENCES USER(user_id),
FOREIGN KEY (game_id) REFERENCES GAME(game_id)
);
-- ALTER TABLE FAVORITE ADD FOREIGN KEY(user_id) REFERENCES USER (user_id)
-- ALTER TABLE FAVORITE ADD FOREIGN KEY(game_id) REFERENCES GAME (game_id)

CREATE TABLE PRICE_ALERT (
user_id INT,
game_id INT,
price DECIMAL(6,2),
PRIMARY KEY (user_id, game_id),
FOREIGN KEY (user_id) REFERENCES USER(user_id),
FOREIGN KEY (game_id) REFERENCES GAME(game_id)
);
-- FOREIGN KEY(/*erro: ??*/) REFERENCES USER (user_id,email)/*falha: chave estrangeira*/

CREATE TABLE STORE (
store_id INT auto_increment PRIMARY KEY,
name VARCHAR(60) UNIQUE
);

CREATE TABLE GAME_PRICES (
game_id INT,
store_name VARCHAR(60),
current_price DECIMAL(6,2),
PRIMARY KEY (game_id, store_name),
FOREIGN KEY (store_name) REFERENCES STORE(name),
FOREIGN KEY (game_id) REFERENCES GAME(game_id)
);
-- ALTER TABLE GAME_PRICES ADD FOREIGN KEY(/*erro: ??*/) REFERENCES STORE (store_id,name)


CREATE TABLE HISTORY (
game_id INT,
store_name VARCHAR(60),
price DECIMAL(6,2),
change_date VARCHAR(60),
FOREIGN KEY(game_id) REFERENCES GAME(game_id),
FOREIGN KEY (store_name) REFERENCES STORE(name)
);
-- FOREIGN KEY(/*erro: ??*/) REFERENCES STORE (store_id,name)


INSERT INTO GENRE VALUES (NULL, 'ACAO');

INSERT INTO GAME VALUES (NULL, (SELECT GENRE_id FROM GENRE WHERE DESCRIPTION = 'ACAO'), 'FOR HONOR', 'UBSOFT', 'FOR HONOR É UM JOGO', NULL, 'LINK FDC');

INSERT INTO USER VALUES(NULL, 'EMAIL@FATEC', 'NOME ALEATORIO', '11945473106', 'S3NH@_@L3@T0R1@');

INSERT INTO FAVORITE VALUES((SELECT USER_id FROM USER WHERE EMAIL = 'EMAIL@FATEC'), (SELECT GAME_id FROM GAME WHERE NAME = 'FOR HONOR'));

INSERT INTO PRICE_ALERT VALUES ( (SELECT USER_id FROM USER WHERE EMAIL = 'EMAIL@FATEC'), (SELECT GAME_id FROM GAME WHERE NAME = 'FOR HONOR'), 15.50);

INSERT INTO STORE VALUES (NULL, 'EPIC STORE');
INSERT INTO STORE VALUES (NULL, 'STEAM');

INSERT INTO GAME_PRICES VALUES ((SELECT GAME_id FROM GAME WHERE NAME = 'FOR HONOR'), 'STEAM', 20.99);


INSERT INTO HISTORY VALUES ((SELECT GAME_id FROM GAME WHERE NAME = 'FOR HONOR'), 'STEAM', 20.99, UNIX_TIMESTAMP());