services:
  buscajogos_db:
    image: mysql:latest
    volumes:
      - ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql  
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: buscajogos
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret